# test:
#   image: $CI_REGISTRY/fmeyer/spotlob:latest
#   stage: test
#   tags:
#     - asprunner
#   script:
#     - source activate spotlob-env
#     - pytest --cov spotlob

test pip:
  image: python:3.7
  stage: test
  tags:
    - asprunner
  script:
    - apt-get update -q -y
    - pip install -r requirements-dev.txt
    - pytest --cov spotlob

test notebooks:
  image: python:3.7
  stage: test
  tags:
    - asprunner
  script:
    - apt-get update -q -y
    - pip install -r requirements-dev.txt
    - pytest --nbval ./notebooks

build doc:
  image: python:3.7
  stage: deploy
  tags:
    - asprunner
  script:
    - apt-get update -q -y
    - apt-get install graphviz -y
    - pip install -r requirements-dev.txt
    - cd docs
    - sphinx-build -W -b html -d _build/doctrees . _build/html
    #- make html

build image:
  image: docker:stable
  stage: deploy
  only:
    refs:
      - master
    changes:
      - dockerfile
      - requirements.yml
  tags:
    - asprunner
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/fmeyer/spotlob .
    - docker push $CI_REGISTRY/fmeyer/spotlob