stages:
  - build
  - test
  - deploy

before_script:
  - pip install -r requirements-dev.txt

build package:
  image: python:3.7
  stage: build
  tags:
    - asprunner
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
    - dist/
    expire_in: 1 week
  cache:
    key: ${CI_COMMIT_REF_SLUG}
  script:
    - python setup.py sdist

build doc:
  image: python:3.7
  stage: build
  tags:
    - asprunner
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
    - docs/_build/html/
    expire_in: 1 week
  script:
    - apt-get update
    - apt-get install graphviz -y
    - cd docs
    - mkdir _static
    - sphinx-build -W -b html -d _build/doctrees . _build/html

test:
  image: python:3.7
  stage: test
  tags:
    - asprunner
  script:
    - pip install pytest tox
    - tox

deploy pypi:
    image: python:3.7
    stage: deploy
    tags:
      - asprunner
    script:
        - pip install -U twine
        - python setup.py sdist
        - twine upload dist/*
    only:
        - tags
    except:
        - branches
