stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .pip

before_script:
  - mkdir -p .pip
  - pip install -U pip
  - pip --cache-dir=.pip install -r requirements-dev.txt

build package:
  image: python:3.7
  stage: build
  tags:
    - asprunner
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
    - dist/
    expire_in: 1 week
  cache:
    key: ${CI_COMMIT_REF_SLUG}
  script:
    - python setup.py sdist

test:
  image: python:3.7
  stage: test
  tags:
    - asprunner
  script:
    - pip install pytest tox
    - tox

test doc build:
  image: python:3.7
  stage: test
  tags:
    - asprunner
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
    - public
    expire_in: 1 week
  script:
    - apt-get update
    - apt-get install graphviz -y
    - cd docs
    - mkdir _static
    - sphinx-build -b html -d _build/doctrees . _build/html
  only:
    - branches

pages:
  image: python:3.7
  stage: deploy
  tags:
    - asprunner
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
    - public
    expire_in: 1 week
  script:
    - apt-get update
    - apt-get install graphviz -y
    - cd docs
    - mkdir _static
    - sphinx-build -b html -d _build/doctrees . _build/html
    - mv _build/html/ ../public/
  only:
    - master

deploy pypi:
  image: python:3.7
  stage: deploy
  tags:
    - asprunner
  script:
      - pip install -U twine
      - python setup.py sdist
      - twine upload dist/*
  only:
      - master
      - tags
