# test:
#   image: $CI_REGISTRY/fmeyer/spotlob:latest
#   stage: test
#   tags:
#     - asprunner
#   script:
#     - source activate spotlob-env
#     - pytest --cov spotlob

test pip:
  image: python:3.7-alpine
  stage: test
  tags:
    - asprunner
  script:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - pytest --cov spotlob

test notebooks:
  image: python:3.7-alpine
  stage: test
  tags:
    - asprunner
  script:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov nbval
    - pytest --nbval ./notebooks

build doc:
  image: python:3.7-alpine
  stage: deploy
  tags:
    - asprunner
  script:
    - apk add graphviz
    - pip install -r requirements-dev.txt
    - cd docs
    - mkdir _static
    - sphinx-build -W -b html -d _build/doctrees . _build/html
    #- make html

build package:
  image: python:3.7-alpine
  stage: deploy
  tags:
    - asprunner
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
    - dist/
    expire_in: 1 week
  script:
    - pip install -r requirements-dev.txt
    - python setup.py sdist


build image:
  image: docker:stable
  stage: deploy
  only:
    refs:
      - master
    changes:
      - dockerfile
      - requirements.yml
  tags:
    - asprunner
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/fmeyer/spotlob .
    - docker push $CI_REGISTRY/fmeyer/spotlob
