build image:
  image: docker:stable
  stage: build
  only:
    changes:
      - dockerfile
      - requirements.yml
  tags:
    - asprunner
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/fmeyer/spotlob .
    - docker push $CI_REGISTRY/fmeyer/spotlob

test:
  image: $CI_REGISTRY/fmeyer/spotlob:latest
  stage: test
  tags:
    - asprunner
  script:
    - source activate spotlob-env
    - pytest --cov spotlob

test pip:
  image: python:3.7
  stage: test
  # only:
  #   changes:
  #     - requirements.txt
  tags:
    - asprunner
  script:
    - apt-get update -q -y
    - pip install -r requirements.txt
    - pytest --cov spotlob

test notebooks:
  image: python:3.7
  stage: test
  tags:
    - asprunner
  script:
    - apt-get update -q -y
    - pip install -r requirements.txt
    - pip install nbval
    - pytest --nbval ./notebooks
