name: spotlob-env
channels:
  - defaults
  - conda-forge
dependencies:
  - opencv>=4.0
  - dill
  - numpy
  - pandas
  - matplotlib
  - ipython
  - ipywidgets
  - pytest
  - pytest-cov
  - setuptools
  - pillow
