name: spotlob-env
channels:
  - defaults
  - conda-forge
dependencies:
  - opencv
  - dill
  - numpy
  - pandas
  - matplotlib
  - ipython
  - ipywidgets
  - pytest
  - pytest-cov
  - pkg_resources
